Add support for MonoCatMysteryBox
alchemyplatform/alchemy-flow-contracts pull request #161
Opened 2022-07-12 05:14 UTC by LemonNekoGH

2022-07-12 17:11 UTC, prpatel05 requested changes

2022-07-12 17:11 UTC, prpatel05 commented on src/cadence/mainnet/getNFTs.cdc
> +pub fun GetMonoCatMysteryBoxNFT(owner: PublicAccount, id: UInt64): NFTData? {
should be `getMonoCatMysteryBoxNFT`

2022-07-12 17:11 UTC, prpatel05 commented on src/cadence/testnet/getNFTs.cdc
> +pub fun GetMonoCatMysteryBoxNFT(owner: PublicAccount, id: UInt64): NFTData? {
same as above

2022-07-13 02:25 UTC, LemonNekoGH commented on src/cadence/mainnet/getNFTs.cdc
> +pub fun GetMonoCatMysteryBoxNFT(owner: PublicAccount, id: UInt64): NFTData? {
sorry

2022-07-26 05:02 UTC, LemonNekoGH commented
@prpatel05 all changes have done

2025-05-29 16:39 UTC, closed without merging