Add_LibraryPass
alchemyplatform/alchemy-flow-contracts pull request #165
Opened 2022-07-15 12:28 UTC by Olive105

2022-07-26 06:01 UTC, thatguyintech commented
hey @albeethekid -- mind reviewing this PR?

2022-07-26 15:39 UTC, prpatel05 requested changes
I would recommend taking a look at https://github.com/alchemyplatform/alchemy-flow-contracts/blob/main/README.md and onboarding to the Catalog as well.  It will be a much simple and more self-service way to make your collection interoperable and discoverable.

2022-07-26 15:39 UTC, prpatel05 commented on src/cadence/mainnet/getNFTs.cdc
> +                case "BreakingT_NFT": d = (owner: owner, id: id)
Looks like a method was removed.

2022-07-26 15:39 UTC, prpatel05 commented on src/cadence/testnet/getNFTs.cdc
> +    let metadata = Gaia.getTemplateMetaData(templateID: nft!.data.templateID)
Same as above

2022-07-27 16:46 UTC, Olive105 commented on src/cadence/mainnet/getNFTs.cdc
> +                case "BreakingT_NFT": d = (owner: owner, id: id)
I added a method

2022-08-01 02:01 UTC, Olive105 reviewed
I fixed the issue and pushed. Please review and let me know. Thanks

2022-08-01 02:09 UTC, Olive105 reviewed
issue - fix issue of metadata

2022-08-05 12:19 UTC, closed without merging

2022-08-05 13:24 UTC, Olive105 commented
Hi Pratik, I removed the old pull request and created a new pull request.
Can you please review and merge asap so that there's no merge conflicts?
https://github.com/alchemyplatform/alchemy-flow-contracts/pull/171
Thanks.
Olive

On Tue, Jul 26, 2022 at 11:40 AM Pratik Patel ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I would recommend taking a look at
> https://github.com/alchemyplatform/alchemy-flow-contracts/blob/main/README.md
> and onboarding to the Catalog as well. It will be a much simple and more
> self-service way to make your collection interoperable and discoverable.
> ------------------------------
>
> In src/cadence/mainnet/getNFTs.cdc
> <https://github.com/alchemyplatform/alchemy-flow-contracts/pull/165#discussion_r930119785>
> :
>
> >                  case "FLOAT" : d = getFLOAT(owner: owner, id: id)
> -                case "BreakingT_NFT": d = getBreakingTNFT(owner: owner, id: id)
> +                case "BreakingT_NFT": d = (owner: owner, id: id)
>
> Looks like a method was removed.
> ------------------------------
>
> In src/cadence/mainnet/getNFTs.cdc
> <https://github.com/alchemyplatform/alchemy-flow-contracts/pull/165#discussion_r930120145>
> :
>
> > +        address: 0x52cbea4e6f616b8e,
> +        storage_path: "LibraryPass.CollectionPath",
> +        public_path: "LibraryPass.CollectionPublicPath",
> +        public_collection_name: "LibraryPass.CollectionPublic",
> +        external_domain: "https://publishednft.io/"
> +    )
> +
> +    let col = owner.getCapability(LibraryPass.CollectionPublicPath)
> +        .borrow<&{LibraryPass.CollectionPublic}>()
> +
> +    if col == nil { return nil }
> +
> +    let nft = col!.borrowLibraryPassNFT(id: id)
> +    if nft == nil { return nil }
> +
> +    let metadata = Gaia.getTemplateMetaData(templateID: nft!.data.templateID)
>
> Do you mean to pull from Gaia here?
> ------------------------------
>
> In src/cadence/testnet/getNFTs.cdc
> <https://github.com/alchemyplatform/alchemy-flow-contracts/pull/165#discussion_r930120662>
> :
>
> > +        address: 0x4d79d7aa8c56c615,
> +        storage_path: "LibraryPass.CollectionPath",
> +        public_path: "LibraryPass.CollectionPublicPath",
> +        public_collection_name: "LibraryPass.CollectionPublic",
> +        external_domain: "https://publishednft.io/"
> +    )
> +
> +    let col = owner.getCapability(LibraryPass.CollectionPublicPath)
> +        .borrow<&{LibraryPass.CollectionPublic}>()
> +
> +    if col == nil { return nil }
> +
> +    let nft = col!.borrowLibraryPassNFT(id: id)
> +    if nft == nil { return nil }
> +
> +    let metadata = Gaia.getTemplateMetaData(templateID: nft!.data.templateID)
>
> Same as above
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alchemyplatform/alchemy-flow-contracts/pull/165#pullrequestreview-1051206185>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP226VOD4IPGXAACBSEIT5LVWABFRANCNFSM53VOK5KA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>