feat - LibraryPass nft
alchemyplatform/alchemy-flow-contracts pull request #91
Opened 2022-04-06 23:52 UTC by Olive105

I added LibraryPass nft. Can you please review and merge? Thanks.

2022-04-08 18:38 UTC, niveda-krish commented
Thanks for submitting this PR - do we plan to support this on testnet? Could you resolve merge conflicts?

2022-04-11 21:19 UTC, niveda-krish commented on src/cadence/mainnet/getNFTIDs.cdc
> +<<<<<<< main
Hi, could you resolve these conflicts?

2022-04-11 22:12 UTC, Olive105 commented
I resolved

2022-04-11 22:12 UTC, Olive105 commented
I resolved

2022-04-15 19:16 UTC, niveda-krish commented
Hey @Olive105 still seeing a bunch of merge conflicts <<< main

2022-04-18 20:32 UTC, niveda-krish commented
Hey @Olive105 reminder to resolve merge conflicts - our biweely release is this Thursday and code will be locked tomorrow

2022-04-18 20:32 UTC, niveda-krish commented
Hey @Olive105 reminder to resolve merge conflicts - our biweely release is this Thursday and code will be locked tomorrow

2022-06-09 16:21 UTC, prpatel05 requested changes
resolve merge conflicts

2022-07-14 18:19 UTC, closed without merging